name: connect_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dcli: ^2.3.0
  path: ^1.9.0
  process_run: ^0.12.5+2
  yaml: ^3.1.1
  ffi: '2.1.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
