include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    include_file_not_found: ignore
    uri_does_not_exist: ignore
    undefined_identifier: ignore
    use_build_context_synchronously: ignore
linter:
  # In addition to the flutter_lints
  rules:
    - always_declare_return_types
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - flutter_style_todos
    - package_api_docs
    - prefer_single_quotes
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_statements
    - unsafe_html
    - use_super_parameters
    - uri_does_not_exist: ignore
    - undefined_identifier: ignore
