name: bookstore
description: Navigation and routing sample app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  adaptive_navigation: ^0.0.3
  collection: ^1.17.0
  connect_flutter_plugin: ^2.33.3-beta
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
