name: connect_cli
description: Connect FLutter Plugin command-line tool for ConnectConfig.json.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <=4.0.0'

# Add regular dependencies here.
dependencies:
  dcli: ^3.4.0
  path: ^1.9.0
  process_run: ^1.0.0+1
  yaml: ^3.1.2
  ffi: '^2.1.0'
  collection: ^1.15.0  # Ensure compatibility
  mime: ^1.0.0  # Ensure compatibility
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
